### ISSUE TITLE
Uncaught TypeError: Cannot redefine property: state

### ISSUE THREAD

**Issue by daviestar** [fabiospampinato/unstated-hmr#1]
Hey, just trying out your library...

Set up like this:
```js
import React from 'react'
import {render} from 'react-dom'
import HMR from 'unstated-hmr'
import App from './App'

HMR.isEnabled = true

render(<App />, document.getElementById('root'))

```
I'm seeing `Uncaught TypeError: Cannot redefine property: state` when I make a change to a component subscribed to an Unstated Container.

Any advice?

I'm using `webpack-dev-server` and my `entry` looks like this:
```js
entry: {
  app: [
    'react-hot-loader/patch',
    'webpack/hot/only-dev-server',
    entryFile
  ]
},
```

**Comment by fabiospampinato** [comment]
Could you perhaps share the whole project or make a sample one in order for me to reproduce the problem exactly?

**Comment by fabiospampinato** [comment]
I think for some reason this line is getting executed multiple times for the same container for you:

https://github.com/fabiospampinato/unstated-hmr/blob/430c449e7ffd0496cf2424a58a706a841836fe37/src/index.ts#L25

It should be an easy fix, but I haven't seen this happening in my app, so I guess yours is doing something different than mine, I'd like to reproduce that situation.

**Comment by daviestar** [comment]
Thanks for the quick response.

Yeah I guessed that line too... I'll see if I can get to the bottom of it, if not I'll post back with a reduced test case.

Cheers!

**Comment by fabiospampinato** [comment]
Let me know if you find out the root cause 👍

**Comment by daviestar** [comment]
Hey,

I spent some time trying to debug this tonight, I created a reduced repo and I still get the same error.

https://github.com/daviestar/react-unstated-hmr-test

For example commenting [this line](https://github.com/daviestar/react-unstated-hmr-test/blob/master/src/Page.js#L17) will cause it.

I'll keep looking and will update this issue if I figure it out.  Cheers.

**Comment by fabiospampinato** [comment]
Thank you, I'm going to try to understand the root cause of this too.

**Comment by fabiospampinato** [comment]
I think I may have found the problem, you are transpiling class properties using `@babel/plugin-proposal-class-properties`, which I think sets them using `Object.defineProperty`, while I'm compiling my code with TypeScript, which instead uses plain assignments for setting class properties.

Now, this library is setting getters and setters in order to catch the first assignment of the state, so it can override it with the previous value. But if you're setting the first assignment using `Object.defineProperty` this doesn't work.

I'm not sure how to fix this, I'll have to think about it.

**Comment by fabiospampinato** [comment]
Ok so I've got it working, I've just published v1.0.3 which better supports code transpiled with babel.

But your project had another problem, the container was being instanciated twice, I have no idea at all why that was happening, maybe webpack HMR isn't configured properly.

This thing was bugging me so I refactored the project a bit, making it more similar to the project I'm using `unstated-hmr` in, and it worked, I've no idea way. 

Check it out for yourself:

[react-unstated-hmr-test-master.zip](https://github.com/fabiospampinato/unstated-hmr/files/2493895/react-unstated-hmr-test-master.zip)

If you'll ever understand what the actual problem with webpack was please do let me know.

**Comment by daviestar** [comment]
Hey again, thanks so much for looking into this! 👍 

> I think I may have found the problem, you are transpiling class properties using @babel/plugin-proposal-class-properties

Interesting, this is a babel plugin that's been in my codebase for ages without much thought (actually while debugging this I removed all the others except this one!).. I'll have a look around to see if this is still the best way to get class properties.

> But your project had another problem, the container was being instanciated twice ... This thing was bugging me so I refactored the project a bit

Yeah, I can confirm that when splitting out `Page` and `PageContainer` to separate files, Page now hot reloads once and preserves state 👍 but PageContainer.js changes cause hot reloading twice - 1st time with old state preserved and 2nd time with initial state.

Would it be possible to see a reduced case where this is working correctly? I'd like to compare what is getting passed between WDM, HMR and RHL.

Thanks.

**Comment by fabiospampinato** [comment]
> Would it be possible to see a reduced case where this is working correctly? I'd like to compare what is getting passed between WDM, HMR and RHL.

I'll probably publish my project in the following 1 or 2 weeks, but it's an electron app compiled via [electron-webpack](https://github.com/electron-userland/electron-webpack), I'm not even sure what its full webpack configuration is. The only thing I added myself about hot reloading is the following:

```ts
if ( module.hot ) {

  module.hot.accept ( './render', () => {
    require ( './render' ).default ();
  });

}
```

**Comment by fabiospampinato** [comment]
> I'll probably publish my project in the following 1 or 2 weeks

Yeah, more like 1 o 2 months. [Here](https://github.com/fabiospampinato/notable) it is. I'm using `unstated-hmr` via [overstated](https://github.com/fabiospampinato/overstated).
